### ISSUE TITLE
Architecture chart link doesn't work

### ISSUE THREAD

**Issue by voideanvalue** [codesandbox/sandpack-bundler#36]
`README.md` has a link to https://www.figma.com/file/I2Gm2pGCRdWMoBWxXrvYib/sandpack-bundler-architecture?node-id=0%3A1 but following the link (and logging into figma) leads me to a page with the following error message

> File not found
>
> Either this file doesn’t exist or you don’t have permission to view it. Ask the file owner to verify the link and/or update permissions.

**Comment by danilowoz** [comment]
Hey, actually, this document is not ready, and it didn't suppose to be public..
I'm removing it
