### ISSUE TITLE
Remove console.warn("Unknown preset parcel, falling back to React") when using experimental bundler

### ISSUE THREAD

**Issue by max-ch9i** [codesandbox/sandpack-bundler#60]
Is it possible to get rid of the warning in console `"Unknown preset parcel, falling back to React"`:
<img width="431" alt="Screenshot 2023-12-11 at 21 10 07" src="https://github.com/codesandbox/sandpack-bundler/assets/1893149/3f1fde1a-a35f-4aec-9fb6-03402633f81d">

My config is as follows.
```jsx
<Sandpack
  template="vanilla"
  options={{
    showConsole: true,
    bundlerURL: "https://sandpack-bundler.codesandbox.io",
  }}
/>
```

**Comment by danilowoz** [comment]
You can omit them for now by using `logLevel`: https://codesandbox.io/p/devbox/unruffled-cdn-n4km2z?file=%2Fsrc%2FApp.tsx%3A14%2C11
